spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tequipy
    username: tequipy
    password: tequipy
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
